Try GoReleaser Pro release
Signed-off-by: Evan Wies <evan@neomantra.net>

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -125,3 +125,18 @@ tasks:
     cmds:
       - rm -rf public
       - hugo --minify
+
+  release:test:
+    desc: Test release build with goreleaser (requires PRO key)
+    cmds:
+      - |
+        if [ -z "$GORELEASER_KEY" ]; then
+          echo "Error: GORELEASER_KEY env var not set"
+          exit 1
+        fi
+      - goreleaser release --snapshot --clean --split
+    env:
+      GORELEASER_CURRENT_GOOS:
+        sh: go env GOOS
+      GORELEASER_CURRENT_GOARCH:
+        sh: go env GOARCH
